version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:16-alpine
    container_name: rencana-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rencana_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rencana-network

  # Next.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rencana-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/rencana_db?schema=public
      - ADMIN_API_TOKEN=${ADMIN_API_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - postgres
    networks:
      - rencana-network

  # n8n for workflow automation and Telegram integration
  n8n:
    image: n8nio/n8n:latest
    container_name: rencana-n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://n8n:5678/
      - GENERIC_TIMEZONE=Asia/Jakarta
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - rencana-network

networks:
  rencana-network:
    driver: bridge

volumes:
  postgres-data:
  n8n-data: